trigger:
  paths:
    include:
      - GptEdge

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: "Build"
    steps:
      - checkout: self
        submodules: "recursive"
        displayName: Checkout source
      - script: |
          sudo apt update
          sudo apt install libcurl4-openssl-dev
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: Install dependencies
      - script: rustup component add clippy
        displayName: Install clippy
      - script: cargo clippy --all
        displayName: Run clippy
        workingDirectory: GptEdge
      - script: cargo build --all
        displayName: Cargo build
        workingDirectory: GptEdge
      - script: cargo test --all
        displayName: Cargo test
        workingDirectory: GptEdge
